name: signalr2
version: 1.0.3+2
description: A dart wrapper around the official SignalR JavaScript library for ASP.NET Core 2.1

homepage: https://github.com/rinukkusu/signalr2-dart
author: 'rinukkusu <rinukkusu@auen.land>'

dependencies: 
  js: ^0.6.1+1
  func2: ^2.0.0

dev_dependencies: 

environment: 
  sdk: ">=2.0.0 <3.0.0"
